cart/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('' ,views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/', views.remove_cart_item, name='remove_cart_item'),
]

shopingcentre/urls.py
from .views import (
    login_user,
    signup,
    home,
    about,
    contact,
    shop,
    logout_user,
    product,
    category,
    update_user,
    update_password,
    update_profile,
    stk_push,
    index,
)
from django.urls import path

app_name = "shopingcentre"
urlpatterns = [
    path("", home, name="home"),
    path("signup/", signup, name="signup"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("shop/", shop, name="shop"),
    path("product/<int:pk>", product, name="product"),
    path("category/<str:foo>", category, name="category"),
    path("update_user/", update_user, name="update_user"),
    path("update_password/", update_password, name="update_password"),
    path("update_profile/", update_profile, name="update_profile"),
    path("checkout/", index, name="checkout"),
    path("stk_push/", stk_push, name="stk_push"),
]

tedsshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopingcentre.urls')),
    path('cart/', include('cart.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopingcentre/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    date_modified=models.DateTimeField(User, auto_now=True)
    phone=models.CharField(max_length=20, blank=True)
    address=models.CharField(max_length=200)
    city=models.CharField(max_length=200)
    state=models.CharField(max_length=200)
    country=models.CharField(max_length=200)
    old_cart= models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        return self.user.username
    
#create a userprofile when a user signup
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile=Profile(user=instance)
        user_profile.save()
        
    #automate the profile saving
post_save.connect(create_profile, sender=User)

class Category(models.Model):
    name = models.CharField(max_length=200)
    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
class Customers(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone= models.CharField(max_length=10)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    
    def __str__(self):
        return self.first_name

# all of our Product

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    #add sell staff
    is_sale=models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    def __str__(self):
        return self.name
# customer orders
class Orders(models.Model):
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    address= models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=20, default='', null=True, blank=True)
    date_ordered = models.DateTimeField(default=datetime.datetime.now)
    status= models.CharField(default=False, max_length=20)
    def __str__(self):
        return str(self.id)

shopingcentre/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from .models import Profile


class UserInfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["phone"].widget.attrs.update(
            {
                "name": "phone",
                "id": "phone",
                "placeholder": "Enter Your Phone Number",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["address"].widget.attrs.update(
            {
                "name": "address",
                "id": "address",
                "placeholder": "Enter Your Current Address",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["city"].widget.attrs.update(
            {
                "name": "city",
                "id": "city",
                "placeholder": "Enter Your Current City",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["country"].widget.attrs.update(
            {
                "name": "country",
                "id": "country",
                "placeholder": "Enter Your Current Country",
                "class": "input-box",
                "type": "text",
            }
        )

    class Meta:
        model = Profile
        fields = ["phone", "address", "city", "country"]


class ChangePasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["new_password1"].widget.attrs.update(
            {
                "name": "password1",
                "id": "password1",
                "placeholder": "Enter Your Password",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["new_password2"].widget.attrs.update(
            {
                "name": "password1",
                "id": "password1",
                "placeholder": "Confirm Your Password",
                "class": "input-box",
                "type": "text",
            }
        )

    class Meta:
        model = User
        fields = ["new_password1", "new_password2"]


class UpdateUserForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = None

        self.fields["username"].widget.attrs.update(
            {
                "name": "username",
                "id": "username",
                "placeholder": "Enter Your Username",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["first_name"].widget.attrs.update(
            {
                "name": "firstname",
                "id": "firstname",
                "placeholder": "Enter Your First Name",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["last_name"].widget.attrs.update(
            {
                "name": "lastname",
                "id": "lastname",
                "placeholder": "Enter Your Last Name",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["email"].widget.attrs.update(
            {
                "name": "email",
                "id": "email",
                "placeholder": "Enter Your Email",
                "class": "input-box",
                "type": "email",
            }
        )

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs.update(
            {
                "name": "password1",
                "id": "password1",
                "placeholder": "Enter Your Password",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["password2"].widget.attrs.update(
            {
                "name": "password2",
                "id": "password2",
                "placeholder": "Confirm Your Password",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["username"].widget.attrs.update(
            {
                "name": "username",
                "id": "username",
                "placeholder": "Enter Username",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["email"].widget.attrs.update(
            {
                "name": "email",
                "id": "email",
                "placeholder": "Enter Your Email",
                "class": "input-box",
                "type": "email",
            }
        )
        self.fields["first_name"].widget.attrs.update(
            {
                "name": "firstname",
                "id": "firstname",
                "placeholder": "Enter Your First Name",
                "class": "input-box",
                "type": "text",
            }
        )
        self.fields["last_name"].widget.attrs.update(
            {
                "name": "lastname",
                "id": "lastname",
                "placeholder": "Enter Your Last Name",
                "class": "input-box",
                "type": "text",
            }
        )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]

shopingcentre/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Profile
from cart.models import Cart, CartItem
from cart.views import cart

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, UpdateUserForm, ChangePasswordForm, UserInfoForm
from django_daraja.mpesa.core import MpesaClient
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required(login_url="shopingcentre:login")
def index(request):
    profile = Profile.objects.get(user_id=request.user)

    cl = MpesaClient()
    # Use a Safaricom phone number that you have access to, for you to be able to view the prompt.
    phone_number = str(profile.phone)
    if phone_number.startswith("0"):
        phone_number = (
            "254" + phone_number[1:]
        )  # Replace leading '0' with '254' for Kenyan numbers
    amount = 5000
    account_reference = "tedShop"
    transaction_desc = "Description"
    callback_url = "https://darajambili.herokuapp.com/express-payment"
    response = cl.stk_push(
        phone_number, amount, account_reference, transaction_desc, callback_url
    )
    return HttpResponse(response)


def stk_push(request):
    data = request.body
    return HttpResponse("STK Push in Django👋")


@login_required(login_url="shopingcentre:login")
def update_profile(request):
    if request.user.is_authenticated:
        current_user = Profile.objects.get(user_id=request.user.id)
        user_form = UserInfoForm(request.POST or None, instance=current_user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Your profile info is updated successfully")
            return redirect("shopingcentre:home")
        return render(request, "update_profile.html", {"user_form": user_form})
    else:
        messages.error(request, "Your are not logged in")
        return redirect("shopingcentre:login")


@login_required(login_url="shopingcentre:login")
def update_password(request):
    if request.user.is_authenticated:
        current_user = request.user
        if request.method == "POST":
            form = ChangePasswordForm(current_user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Password changed successfully")
                return redirect("shopingcentre:login")
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                    return redirect("shopingcentre:login")
        else:
            form = ChangePasswordForm(current_user)
            return render(request, "update_password.html", {"form": form})
    else:

        return redirect("shopingcentre:login")


@login_required(login_url="shopingcentre:login")
def update_user(request):

    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        user_form = UpdateUserForm(request.POST or None, instance=current_user)
        if user_form.is_valid():
            user_form.save()
            login(request, current_user)
            messages.success(request, "Your profile is updated successfully")
            return redirect("shopingcentre:home")
        return render(request, "update_user.html", {"user_form": user_form})
    else:
        messages.error(request, "Your are not logged in")
        return redirect("shopingcentre:login")


def login_user(request):
    if request.method == "POST":
        # Retrieve the username and password safely
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Check if both fields are provided
        if not username or not password:
            messages.error(request, "Both username and password are required")
            return render(request, "login.html")

        # Authenticate the user
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            messages.error(request, "Username or password is incorrect")

    return render(request, "login.html")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            email = form.cleaned_data["email"]
            user = authenticate(username=username, password=password, email=email)
            login(request, user)
            messages.success(request, "Account was created successfully")
            return redirect("shopingcentre:update_profile")
    else:
        form = SignUpForm()

    return render(request, "signup.html", {"form": form})


@login_required(login_url="shopingcentre:login")
def logout_user(request):
    logout(request)
    return redirect("/")


def home(request):
    return render(request, "landing_page.html")


def about(request):
    return render(request, "about.html")


def contact(request):
    return render(request, "contact.html")


def shop(request):
    products = Product.objects.all()
    context = {"products": products}
    return render(request, "shop.html", context)


def product(request, pk):
    product = Product.objects.get(id=pk)
    context = {"product": product}
    return render(request, "product.html", context)


def category(request, foo):
    foo = foo.replace("-", " ")
    # grab the category from the url\\
    try:
        # lookup the category
        category = Category.objects.get(name=foo)
        # get all products in that category
        products = Product.objects.filter(category=category)
        return render(
            request, "category.html", {"products": products, "category": category}
        )
    except:
        messages.success(request, "Category does not exist")
        return redirect("/")

shopingcentre/templates/cart_summary.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Cart</title>    
{% endblock title %}
{% block content %}

    <div class="cart-container">
        {% if not cart_items %}
            <h1 style="text-align: center;">Your Shoping Cart Is Empty</h1>
            <div class="text-centre">
                <a href="{%url 'shopingcentre:shop'%}" class="shop">Continue Shoping</a>
            </div>
        {% else %}
        
        <div class="cart-content">
            {% for cart_item in cart_items  %}
            <div class="cart-item">
                <img src="{{cart_item.product.image.url}}" alt="image1" class="carImg">
                <div class="cart-text">
                    <h1>{{cart_item.product.name}}</h1>
                    <p class="price">Kshs {{cart_item.product.price}}</p>
                    <p class="total-price">Total cost: Kshs {{cart_item.subtotal}}</p>
                    <div class="quantity">
                        <p>Quantity</p>
                        <input type="number" value="{{cart_item.quantity}}" >
                    </div>
                    <a href="{% url 'remove_cart_item' cart_item.product.id%}">Delete</a>
                    <div class="calculate">
                        <div class="minus">
                            <a href="{% url 'remove_cart' cart_item.product.id%}"><i class="fas fa-minus"></i></a>
                        </div>
                        <div class="plus">
                            <a href="{% url 'add_cart' cart_item.product.id%}"><i class="fas fa-plus"></i></a>
                        </div>
                    </div>
                </div>
            </div> 
            {% endfor %} 
        </div>
        <div class="checkout-container">
            <div class="check-content">
                <div class="subtotal">
                    <p class="check">Subtotal</p>
                    <p >Kshs {{total}}</p>
                </div>
                <div class="shipping">
                    <p class="check">Tax</p>
                    <p>Kshs {{tax}}</p>
                </div>
                <div class="total">
                    <p class="check">Grand Total</p>
                    <p>Kshs {{grand_total}}</p>
                </div>
                
            </div>
            <div class="Payment">
                <div class="make-payment">
                    <a href=" {% url "shopingcentre:checkout" %}">Make Payment</a>
                </div>
                <div class="continue">
                    <a href=" {% url "shopingcentre:shop" %}">Continue Shopping</a>
                </div>
                
            </div>
            {% endif %}
    </div>
{% endblock content %}

shopingcentre/templates/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Shop</title>
{% endblock title %}
{% block content %}
    <div class="shop">
        <div class="about-content">
            <img src="{% static 'images/darksho.jpg' %}" alt="image1">
            <h2>Shop In Style with</h2>
            <h1>TedShop</h1>
        </div>
        <div class="shop-container">
            <div class="shop-type">
                <div class="shop-categories">
                    <h1>Categories</h1>
                    <ul class="category">
                        <li><a href="{% url "shopingcentre:shop" %}">All</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'Women' %}">Women</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'men' %}">Men</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'Children' %}">Children</a> </li>
                    </ul>
                </div>

            </div>
        </div>
        <div class="shop-container-item">
            <div class="shop-item">
                {% for product in products %}
                {% if product.is_sale  %}
                <div class="shop-content">
                    <div class="sale">Sale</div>
                    <img src="{{product.image.url}}" alt="image1">
                    <h1>{{product.name}}</h1>
                    <p class="price"><strike>${{product.price}}</strike>&nbsp;${{product.sale_price}}</p>
                    
                </div>
                {% else %}
                <div class="shop-content">
                    <img src="{{product.image.url}}" alt="image1">
                    <div class="cart"></div>
                    <h1>{{product.name}}</h1>
                    <p class="price">${{product.price}}</p>
                </div>
                {% endif %}
                <div class="view">
                    <div class="cartLink">
                        <a href="" value="{{product.id}}" id="addCart" >Add to cart</a>
                    </div>
                    <div class="viewLink">
                        <a href=" {% url 'shopingcentre:product' pk=product.id %}">View Product</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

shopingcentre/templates/landing_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}<title>Home</title>{% endblock title %}
    {% block content %}
        <section class="home ">
            <div class="home-content ">
                <div class="home-text ">
                    <h1>Shop Online</h1>
                    <p>Shop online with us and get the best deals</p>
                </div>
                <div class="image-slider ">
                    <div class="slide active">
                        <img src="{% static 'images/handbag.jpg' %}" alt="image1">
                        <div class="slide-info">
                            <h2>Women's Fashion 2024  </h2>
                            <h1>new arrivals</h1>
                            <a href=" {% url "shopingcentre:shop" %}">Shopping</a>
                        </div>
                    </div>
                    <div class="slide ">
                        <img src="{% static 'images/shoes.jpg' %}" alt="image1">
                        <div class="slide-info">
                            <h2>Men's Fashion 2024  </h2>
                            <h1>new arrivals</h1>
                            <a href=" {% url "shopingcentre:shop" %}">Shopping</a>
                        </div>
                    </div>
                    <div class="slide ">
                        <img src="{% static 'images/coat.jpg' %}" alt="image1">
                        <div class="slide-info">
                            <h2>Children's Fashion 2024  </h2>
                            <h1>new arrivals</h1>
                            <a href=" {% url "shopingcentre:shop" %}">Shopping</a>
                        </div>
                    </div>
                    <div class="navigation" >
                        <div class="radio active"></div>
                        <div class="radio"></div>
                        <div class="radio"></div>
                    </div>
                </div>
            </div>
        </section>
        <script src="{% static 'js/app.js' %}"></script>
    {% endblock content %}

shopingcentre/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title> Login</title>
{% endblock title %}
{% block content %}
<div class="form-cont">
    <div class="contain">
        <div class="form-box login">
            
            <form action="" method="POST">
                {% csrf_token %}
                <h1>Login</h1>
                <div class="input-box">
                    <input type="text" name="username" placeholder="Username" required>
                    <i class='bx bxs-user' ></i>
                </div>
                <div class="input-box">
                    <input type="password" name="password" placeholder="Password" required>
                    <i class='bx bxs-lock-alt' ></i>
                </div>
                <div class="forgot-password">
                    <a href="#">Forgot Password?</a>
                </div>
                <button type="submit" class="btn">Login</button>
                <p>or login with social account</p>
                <div class="social-icons">
                    <a href=""><i class='bx bxl-google' ></i></a>
                    <a href=""><i class='bx bxl-facebook' ></i></a>
                    <a href=""><i class='bx bxl-twitter' ></i></a>
                </div>
            </form>
        </div>
        <div class="toggle-box">
            <div class="toggle-panel toggle-left">
                <h1>Hello, Welcome</h1>
                <p>Don't have a account ?</p>
                <a href="{% url 'shopingcentre:signup' %}"><button class="btn register-btn">Sign-Up</button></a>
            </div>            
        </div>
    </div>
</div>
<script src="{% static 'js/app.js' %}"></script>
{% endblock content %}

shopingcentre/templates/nav-header.html
{% comment %} mobile screen {% endcomment %}
{% comment %} end of mobile screen {% endcomment %}
<div class="nav-header">
    <div class="nav-logo">
        <h1>TedShop <span class="logo"></span></h1>
    </div>
    <nav class="links" id="links">
        <li><a href="{% url 'shopingcentre:home' %}">Home</a></li>
        <li><a href="{% url 'shopingcentre:shop'%}">Shop</a></li>
        <li><a href="{% url 'shopingcentre:about'%}">About</a></li>
        <li><a href="{% url 'shopingcentre:contact'%}">Contact Us</a></li>
    </nav>
    <div class="icons-content">
        <div class="authentication">
            <i class="fas fa-user"></i>
            <i class="fas fa-caret-down arrow"></i>
            <div class="auth">
                {% if user.is_authenticated %}
                <a href="{% url 'shopingcentre:logout'%}">Logout</a>
                <a href="{% url 'shopingcentre:update_user'%}">Profile</a>
                {% else  %}
                <a href="{% url 'shopingcentre:login'%}">Login</a>
                <a href="{% url 'shopingcentre:signup'%}">Register</a>
                {% endif %}
            </div>
        </div>
        <div class="cart-icon">
            <a href="{% url 'cart'%}">
                <i class="fas fa-shopping-cart"></i>
                <span class="cart-count">{{cart_count}}</span>
            </a>
            
        </div>
        
        </div>
    </div>
</div>

shopingcentre/templates/product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="product">
    <div class="back"><a href=" {% url 'shopingcentre:shop'%}">Back</a></div>
    <div class="img-container">
        <div class="big-image">
            <img src="{{ product.image.url}}" alt="">
        </div>
        <div class="small-images">
            <div class="small">
                <img src="{{product.image.url}}" onclick ="showImg(this.src)" class="img1"alt="" >
            </div>
            <div class="small">
                <img src="{{product.image.url}}" onclick ="showImg(this.src)" alt="" >
            </div>
            <div class="small">
                <img src="{{product.image.url}}" onclick ="showImg(this.src)" alt="" >
            </div>
        </div>
    </div>
    <div class="product-content">
        <h1 class="product-name">{{product.name}}</h1>
        <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
        </div>
        <h1 class="product-price">Kshs {{product.price}}</h1>
        <div class="product-size">
            <div class="psize">M</div>
            <div class="psize">L</div>
            <div class="psize">XL</div>
            <div class="psize">XXL</div>
        </div>
        <div class="product-quantity">
            <p>Quantity</p>
            <input type="number" name="" id="" min="1" value="1" max="5">
        </div>
        <div class="product-btn">
            <a href="{% url 'add_cart' product_id=product.id %}" class="addCart" role="button" aria-pressed="true" data-toggle="modal" data-target="#exampleModal"value="{{product.id}}" id="addCart">Add Cart</a>
        </div>
    </div>
</section>

<script src="{% static 'js/app.js' %}"></script>
{% endblock content %}

shopingcentre/templates/shop.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Shop</title>
{% endblock title %}
{% block content %}
    <div class="shop">
        <div class="about-content">
            <img src="{% static 'images/darksho.jpg' %}" alt="image1">
            <h2>Shop In Style with</h2>
            <h1>TedShop</h1>
        </div>
        <div class="shop-container">
            <div class="shop-type">
                <div class="shop-categories">
                    <h1>Categories</h1>
                    <ul class="category">
                        <li><a href="{% url "shopingcentre:shop" %}">All</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'Women' %}">Women</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'men' %}">Men</a> </li>
                        <li><a href="{% url "shopingcentre:category" 'Children' %}">Children</a> </li>
                    </ul>
                </div>
                
            </div>
        </div>
        <div class="shop-container-item">
            <div class="shop-item">
                {% for product in products %}
                {% if product.is_sale  %}
                <div class="shop-content">
                    <div class="sale">Sale</div>
                    <img src="{{product.image.url}}" alt="image1">
                    <h1>{{product.name}}</h1>
                    <p class="price"><strike>Kshs{{product.price}}</strike>&nbsp;Kshs{{product.sale_price}}</p>
                </div>
                {% else %}
                <div class="shop-content">
                    <img src="{{product.image.url}}" alt="image1">
                    <div class="cart"></div>
                    <h1>{{product.name}}</h1>
                    <p class="price">Kshs{{product.price}}</p>
                </div>
                {% endif %}
                <div class="view">
                    <div class="cartLink">
                        <a href="{% url 'add_cart' product_id=product.id %}" class="addCart" role="button" aria-pressed="true" data-toggle="modal" data-target="#exampleModal"value="{{product.id}}" id="addCart">Add Cart</a>
                    </div>
                    <div class="viewLink">
                        <a href=" {% url 'shopingcentre:product' pk=product.id %}">View Product</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% endblock content %}